### ISSUE TITLE
**유저의 멤버쉽 등급을 업데이트 하는 기준 의견나누기**

### ISSUE THREAD

**Issue by finite2030** [ssg-240304-java2/OOP-PssUsChicken#15]
#### 먼저 멤버쉽 등급은 4가지가 있습니다.
- 브론즈 (일반등급) : 할인율 없음
- 실버 : 상품 가격의 할인율 0.1%
- 골드 : 상품 가격의 할인율 0.2%
- VIP : 상품 가격의 할인율 0.3%

#### 유저의 멤버쉽 등급을 업데이트 하는 기준입니다.
등급은 주문 회수에 따라 업데이트 됩니다.
- 브론즈 (일반등급) : 첫 회원 가입
- 실버 : 주문 1회 시 등급 업데이트
- 골드 : 주문 2회 시 등급 업데이트
- VIP : 주문 3회 시 등급 업데이트

**Comment by DokaDev** [comment]
`주문횟수` : `User` > `Order List Size`

멤버십 업데이트 로직은 우선 `User`에 작성해 두겠습니다. 
@wlsdn 주문 로직 후반부(주문 객체 생성 완료 후) User에서 `updateMembership() : void` 한 번 불러주세요. 주문실적 자체심사 후 업데이트하는 로직입니다.
